version: '3.7'
services:
   db:
      image: postgres:15
      container_name: db_app
      command: -p 5432
      expose:
         - 5432
      env_file:
         - .env

   app:
      build: .
      env_file:
         - .env
      container_name: fastapi_app
      command: ['/fastapi_app/app.sh']
      ports:
         - 8000:8000
      depends_on:
         - db