"""Init

Revision ID: 28c1bd2df736
Revises: 
Create Date: 2024-05-07 03:26:02.176895

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '28c1bd2df736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permissions', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hashed_id', sa.String(), nullable=True, unique=True),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('order_id', sa.Integer(), nullable=False, autoincrement=True),
                    sa.Column('client_hid', sa.String(), nullable=True),
                    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
                    sa.Column('finish_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('shipper_st_code', sa.Integer(), nullable=False),
                    sa.Column("consignee_st_code", sa.Integer, nullable=False),
                    sa.Column('cargo_code', sa.Integer(), nullable=False),
                    sa.Column('cargo_weight', sa.Float(), nullable=False),
                    sa.Column('services', sa.JSON(), nullable=True),
                    sa.Column("status", sa.String(), nullable=True, default="Создан"),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_table('search_history',
                    sa.Column('search_id', sa.Integer(), nullable=False, autoincrement=True),
                    sa.Column('client_hid', sa.String(), nullable=True),
                    sa.Column("search_time", sa.TIMESTAMP(), nullable=True),
                    sa.Column('doc_state', sa.String(), nullable=False),
                    sa.Column('start_date', sa.TIMESTAMP(), nullable=False),
                    sa.Column('finish_date', sa.TIMESTAMP(), nullable=True),
                    sa.Column('shipper_st_code', sa.Integer(), nullable=False),
                    sa.Column("consignee_st_code", sa.Integer, nullable=False),
                    sa.Column('cargo_code', sa.Integer(), nullable=False),
                    sa.Column('cargo_weight', sa.Float(), nullable=False),
                    sa.Column('services', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['client_hid'], ['user.hashed_id'], ),
                    sa.PrimaryKeyConstraint('search_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
